// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/chain-middleware/pkg/db/ent/coinfiatcurrency"
	"github.com/NpoolPlatform/chain-middleware/pkg/db/ent/predicate"
)

// CoinFiatCurrencyDelete is the builder for deleting a CoinFiatCurrency entity.
type CoinFiatCurrencyDelete struct {
	config
	hooks    []Hook
	mutation *CoinFiatCurrencyMutation
}

// Where appends a list predicates to the CoinFiatCurrencyDelete builder.
func (cfcd *CoinFiatCurrencyDelete) Where(ps ...predicate.CoinFiatCurrency) *CoinFiatCurrencyDelete {
	cfcd.mutation.Where(ps...)
	return cfcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cfcd *CoinFiatCurrencyDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cfcd.hooks) == 0 {
		affected, err = cfcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoinFiatCurrencyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cfcd.mutation = mutation
			affected, err = cfcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cfcd.hooks) - 1; i >= 0; i-- {
			if cfcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cfcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cfcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfcd *CoinFiatCurrencyDelete) ExecX(ctx context.Context) int {
	n, err := cfcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cfcd *CoinFiatCurrencyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: coinfiatcurrency.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: coinfiatcurrency.FieldID,
			},
		},
	}
	if ps := cfcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cfcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// CoinFiatCurrencyDeleteOne is the builder for deleting a single CoinFiatCurrency entity.
type CoinFiatCurrencyDeleteOne struct {
	cfcd *CoinFiatCurrencyDelete
}

// Exec executes the deletion query.
func (cfcdo *CoinFiatCurrencyDeleteOne) Exec(ctx context.Context) error {
	n, err := cfcdo.cfcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{coinfiatcurrency.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cfcdo *CoinFiatCurrencyDeleteOne) ExecX(ctx context.Context) {
	cfcdo.cfcd.ExecX(ctx)
}
