// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/chain-middleware/pkg/db/ent/coinfiat"
	"github.com/google/uuid"
)

// CoinFiatCreate is the builder for creating a CoinFiat entity.
type CoinFiatCreate struct {
	config
	mutation *CoinFiatMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (cfc *CoinFiatCreate) SetCreatedAt(u uint32) *CoinFiatCreate {
	cfc.mutation.SetCreatedAt(u)
	return cfc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cfc *CoinFiatCreate) SetNillableCreatedAt(u *uint32) *CoinFiatCreate {
	if u != nil {
		cfc.SetCreatedAt(*u)
	}
	return cfc
}

// SetUpdatedAt sets the "updated_at" field.
func (cfc *CoinFiatCreate) SetUpdatedAt(u uint32) *CoinFiatCreate {
	cfc.mutation.SetUpdatedAt(u)
	return cfc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cfc *CoinFiatCreate) SetNillableUpdatedAt(u *uint32) *CoinFiatCreate {
	if u != nil {
		cfc.SetUpdatedAt(*u)
	}
	return cfc
}

// SetDeletedAt sets the "deleted_at" field.
func (cfc *CoinFiatCreate) SetDeletedAt(u uint32) *CoinFiatCreate {
	cfc.mutation.SetDeletedAt(u)
	return cfc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cfc *CoinFiatCreate) SetNillableDeletedAt(u *uint32) *CoinFiatCreate {
	if u != nil {
		cfc.SetDeletedAt(*u)
	}
	return cfc
}

// SetEntID sets the "ent_id" field.
func (cfc *CoinFiatCreate) SetEntID(u uuid.UUID) *CoinFiatCreate {
	cfc.mutation.SetEntID(u)
	return cfc
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (cfc *CoinFiatCreate) SetNillableEntID(u *uuid.UUID) *CoinFiatCreate {
	if u != nil {
		cfc.SetEntID(*u)
	}
	return cfc
}

// SetCoinTypeID sets the "coin_type_id" field.
func (cfc *CoinFiatCreate) SetCoinTypeID(u uuid.UUID) *CoinFiatCreate {
	cfc.mutation.SetCoinTypeID(u)
	return cfc
}

// SetNillableCoinTypeID sets the "coin_type_id" field if the given value is not nil.
func (cfc *CoinFiatCreate) SetNillableCoinTypeID(u *uuid.UUID) *CoinFiatCreate {
	if u != nil {
		cfc.SetCoinTypeID(*u)
	}
	return cfc
}

// SetFiatID sets the "fiat_id" field.
func (cfc *CoinFiatCreate) SetFiatID(u uuid.UUID) *CoinFiatCreate {
	cfc.mutation.SetFiatID(u)
	return cfc
}

// SetNillableFiatID sets the "fiat_id" field if the given value is not nil.
func (cfc *CoinFiatCreate) SetNillableFiatID(u *uuid.UUID) *CoinFiatCreate {
	if u != nil {
		cfc.SetFiatID(*u)
	}
	return cfc
}

// SetFeedType sets the "feed_type" field.
func (cfc *CoinFiatCreate) SetFeedType(s string) *CoinFiatCreate {
	cfc.mutation.SetFeedType(s)
	return cfc
}

// SetNillableFeedType sets the "feed_type" field if the given value is not nil.
func (cfc *CoinFiatCreate) SetNillableFeedType(s *string) *CoinFiatCreate {
	if s != nil {
		cfc.SetFeedType(*s)
	}
	return cfc
}

// SetID sets the "id" field.
func (cfc *CoinFiatCreate) SetID(i int) *CoinFiatCreate {
	cfc.mutation.SetID(i)
	return cfc
}

// Mutation returns the CoinFiatMutation object of the builder.
func (cfc *CoinFiatCreate) Mutation() *CoinFiatMutation {
	return cfc.mutation
}

// Save creates the CoinFiat in the database.
func (cfc *CoinFiatCreate) Save(ctx context.Context) (*CoinFiat, error) {
	var (
		err  error
		node *CoinFiat
	)
	if err := cfc.defaults(); err != nil {
		return nil, err
	}
	if len(cfc.hooks) == 0 {
		if err = cfc.check(); err != nil {
			return nil, err
		}
		node, err = cfc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoinFiatMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cfc.check(); err != nil {
				return nil, err
			}
			cfc.mutation = mutation
			if node, err = cfc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cfc.hooks) - 1; i >= 0; i-- {
			if cfc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cfc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cfc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CoinFiat)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CoinFiatMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cfc *CoinFiatCreate) SaveX(ctx context.Context) *CoinFiat {
	v, err := cfc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cfc *CoinFiatCreate) Exec(ctx context.Context) error {
	_, err := cfc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfc *CoinFiatCreate) ExecX(ctx context.Context) {
	if err := cfc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cfc *CoinFiatCreate) defaults() error {
	if _, ok := cfc.mutation.CreatedAt(); !ok {
		if coinfiat.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized coinfiat.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := coinfiat.DefaultCreatedAt()
		cfc.mutation.SetCreatedAt(v)
	}
	if _, ok := cfc.mutation.UpdatedAt(); !ok {
		if coinfiat.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coinfiat.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coinfiat.DefaultUpdatedAt()
		cfc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cfc.mutation.DeletedAt(); !ok {
		if coinfiat.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized coinfiat.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := coinfiat.DefaultDeletedAt()
		cfc.mutation.SetDeletedAt(v)
	}
	if _, ok := cfc.mutation.EntID(); !ok {
		if coinfiat.DefaultEntID == nil {
			return fmt.Errorf("ent: uninitialized coinfiat.DefaultEntID (forgotten import ent/runtime?)")
		}
		v := coinfiat.DefaultEntID()
		cfc.mutation.SetEntID(v)
	}
	if _, ok := cfc.mutation.CoinTypeID(); !ok {
		if coinfiat.DefaultCoinTypeID == nil {
			return fmt.Errorf("ent: uninitialized coinfiat.DefaultCoinTypeID (forgotten import ent/runtime?)")
		}
		v := coinfiat.DefaultCoinTypeID()
		cfc.mutation.SetCoinTypeID(v)
	}
	if _, ok := cfc.mutation.FiatID(); !ok {
		if coinfiat.DefaultFiatID == nil {
			return fmt.Errorf("ent: uninitialized coinfiat.DefaultFiatID (forgotten import ent/runtime?)")
		}
		v := coinfiat.DefaultFiatID()
		cfc.mutation.SetFiatID(v)
	}
	if _, ok := cfc.mutation.FeedType(); !ok {
		v := coinfiat.DefaultFeedType
		cfc.mutation.SetFeedType(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (cfc *CoinFiatCreate) check() error {
	if _, ok := cfc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CoinFiat.created_at"`)}
	}
	if _, ok := cfc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CoinFiat.updated_at"`)}
	}
	if _, ok := cfc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "CoinFiat.deleted_at"`)}
	}
	if _, ok := cfc.mutation.EntID(); !ok {
		return &ValidationError{Name: "ent_id", err: errors.New(`ent: missing required field "CoinFiat.ent_id"`)}
	}
	return nil
}

func (cfc *CoinFiatCreate) sqlSave(ctx context.Context) (*CoinFiat, error) {
	_node, _spec := cfc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cfc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (cfc *CoinFiatCreate) createSpec() (*CoinFiat, *sqlgraph.CreateSpec) {
	var (
		_node = &CoinFiat{config: cfc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: coinfiat.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: coinfiat.FieldID,
			},
		}
	)
	_spec.OnConflict = cfc.conflict
	if id, ok := cfc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cfc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinfiat.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := cfc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinfiat.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := cfc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinfiat.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := cfc.mutation.EntID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: coinfiat.FieldEntID,
		})
		_node.EntID = value
	}
	if value, ok := cfc.mutation.CoinTypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: coinfiat.FieldCoinTypeID,
		})
		_node.CoinTypeID = value
	}
	if value, ok := cfc.mutation.FiatID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: coinfiat.FieldFiatID,
		})
		_node.FiatID = value
	}
	if value, ok := cfc.mutation.FeedType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coinfiat.FieldFeedType,
		})
		_node.FeedType = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinFiat.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinFiatUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cfc *CoinFiatCreate) OnConflict(opts ...sql.ConflictOption) *CoinFiatUpsertOne {
	cfc.conflict = opts
	return &CoinFiatUpsertOne{
		create: cfc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinFiat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cfc *CoinFiatCreate) OnConflictColumns(columns ...string) *CoinFiatUpsertOne {
	cfc.conflict = append(cfc.conflict, sql.ConflictColumns(columns...))
	return &CoinFiatUpsertOne{
		create: cfc,
	}
}

type (
	// CoinFiatUpsertOne is the builder for "upsert"-ing
	//  one CoinFiat node.
	CoinFiatUpsertOne struct {
		create *CoinFiatCreate
	}

	// CoinFiatUpsert is the "OnConflict" setter.
	CoinFiatUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *CoinFiatUpsert) SetCreatedAt(v uint32) *CoinFiatUpsert {
	u.Set(coinfiat.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinFiatUpsert) UpdateCreatedAt() *CoinFiatUpsert {
	u.SetExcluded(coinfiat.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinFiatUpsert) AddCreatedAt(v uint32) *CoinFiatUpsert {
	u.Add(coinfiat.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinFiatUpsert) SetUpdatedAt(v uint32) *CoinFiatUpsert {
	u.Set(coinfiat.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinFiatUpsert) UpdateUpdatedAt() *CoinFiatUpsert {
	u.SetExcluded(coinfiat.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinFiatUpsert) AddUpdatedAt(v uint32) *CoinFiatUpsert {
	u.Add(coinfiat.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinFiatUpsert) SetDeletedAt(v uint32) *CoinFiatUpsert {
	u.Set(coinfiat.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinFiatUpsert) UpdateDeletedAt() *CoinFiatUpsert {
	u.SetExcluded(coinfiat.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinFiatUpsert) AddDeletedAt(v uint32) *CoinFiatUpsert {
	u.Add(coinfiat.FieldDeletedAt, v)
	return u
}

// SetEntID sets the "ent_id" field.
func (u *CoinFiatUpsert) SetEntID(v uuid.UUID) *CoinFiatUpsert {
	u.Set(coinfiat.FieldEntID, v)
	return u
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CoinFiatUpsert) UpdateEntID() *CoinFiatUpsert {
	u.SetExcluded(coinfiat.FieldEntID)
	return u
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinFiatUpsert) SetCoinTypeID(v uuid.UUID) *CoinFiatUpsert {
	u.Set(coinfiat.FieldCoinTypeID, v)
	return u
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinFiatUpsert) UpdateCoinTypeID() *CoinFiatUpsert {
	u.SetExcluded(coinfiat.FieldCoinTypeID)
	return u
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *CoinFiatUpsert) ClearCoinTypeID() *CoinFiatUpsert {
	u.SetNull(coinfiat.FieldCoinTypeID)
	return u
}

// SetFiatID sets the "fiat_id" field.
func (u *CoinFiatUpsert) SetFiatID(v uuid.UUID) *CoinFiatUpsert {
	u.Set(coinfiat.FieldFiatID, v)
	return u
}

// UpdateFiatID sets the "fiat_id" field to the value that was provided on create.
func (u *CoinFiatUpsert) UpdateFiatID() *CoinFiatUpsert {
	u.SetExcluded(coinfiat.FieldFiatID)
	return u
}

// ClearFiatID clears the value of the "fiat_id" field.
func (u *CoinFiatUpsert) ClearFiatID() *CoinFiatUpsert {
	u.SetNull(coinfiat.FieldFiatID)
	return u
}

// SetFeedType sets the "feed_type" field.
func (u *CoinFiatUpsert) SetFeedType(v string) *CoinFiatUpsert {
	u.Set(coinfiat.FieldFeedType, v)
	return u
}

// UpdateFeedType sets the "feed_type" field to the value that was provided on create.
func (u *CoinFiatUpsert) UpdateFeedType() *CoinFiatUpsert {
	u.SetExcluded(coinfiat.FieldFeedType)
	return u
}

// ClearFeedType clears the value of the "feed_type" field.
func (u *CoinFiatUpsert) ClearFeedType() *CoinFiatUpsert {
	u.SetNull(coinfiat.FieldFeedType)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CoinFiat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coinfiat.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinFiatUpsertOne) UpdateNewValues() *CoinFiatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(coinfiat.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.CoinFiat.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *CoinFiatUpsertOne) Ignore() *CoinFiatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinFiatUpsertOne) DoNothing() *CoinFiatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinFiatCreate.OnConflict
// documentation for more info.
func (u *CoinFiatUpsertOne) Update(set func(*CoinFiatUpsert)) *CoinFiatUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinFiatUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinFiatUpsertOne) SetCreatedAt(v uint32) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinFiatUpsertOne) AddCreatedAt(v uint32) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinFiatUpsertOne) UpdateCreatedAt() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinFiatUpsertOne) SetUpdatedAt(v uint32) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinFiatUpsertOne) AddUpdatedAt(v uint32) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinFiatUpsertOne) UpdateUpdatedAt() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinFiatUpsertOne) SetDeletedAt(v uint32) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinFiatUpsertOne) AddDeletedAt(v uint32) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinFiatUpsertOne) UpdateDeletedAt() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetEntID sets the "ent_id" field.
func (u *CoinFiatUpsertOne) SetEntID(v uuid.UUID) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetEntID(v)
	})
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CoinFiatUpsertOne) UpdateEntID() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateEntID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinFiatUpsertOne) SetCoinTypeID(v uuid.UUID) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinFiatUpsertOne) UpdateCoinTypeID() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *CoinFiatUpsertOne) ClearCoinTypeID() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetFiatID sets the "fiat_id" field.
func (u *CoinFiatUpsertOne) SetFiatID(v uuid.UUID) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetFiatID(v)
	})
}

// UpdateFiatID sets the "fiat_id" field to the value that was provided on create.
func (u *CoinFiatUpsertOne) UpdateFiatID() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateFiatID()
	})
}

// ClearFiatID clears the value of the "fiat_id" field.
func (u *CoinFiatUpsertOne) ClearFiatID() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.ClearFiatID()
	})
}

// SetFeedType sets the "feed_type" field.
func (u *CoinFiatUpsertOne) SetFeedType(v string) *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetFeedType(v)
	})
}

// UpdateFeedType sets the "feed_type" field to the value that was provided on create.
func (u *CoinFiatUpsertOne) UpdateFeedType() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateFeedType()
	})
}

// ClearFeedType clears the value of the "feed_type" field.
func (u *CoinFiatUpsertOne) ClearFeedType() *CoinFiatUpsertOne {
	return u.Update(func(s *CoinFiatUpsert) {
		s.ClearFeedType()
	})
}

// Exec executes the query.
func (u *CoinFiatUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinFiatCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinFiatUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CoinFiatUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CoinFiatUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CoinFiatCreateBulk is the builder for creating many CoinFiat entities in bulk.
type CoinFiatCreateBulk struct {
	config
	builders []*CoinFiatCreate
	conflict []sql.ConflictOption
}

// Save creates the CoinFiat entities in the database.
func (cfcb *CoinFiatCreateBulk) Save(ctx context.Context) ([]*CoinFiat, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cfcb.builders))
	nodes := make([]*CoinFiat, len(cfcb.builders))
	mutators := make([]Mutator, len(cfcb.builders))
	for i := range cfcb.builders {
		func(i int, root context.Context) {
			builder := cfcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoinFiatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cfcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cfcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cfcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cfcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cfcb *CoinFiatCreateBulk) SaveX(ctx context.Context) []*CoinFiat {
	v, err := cfcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cfcb *CoinFiatCreateBulk) Exec(ctx context.Context) error {
	_, err := cfcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfcb *CoinFiatCreateBulk) ExecX(ctx context.Context) {
	if err := cfcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinFiat.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinFiatUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cfcb *CoinFiatCreateBulk) OnConflict(opts ...sql.ConflictOption) *CoinFiatUpsertBulk {
	cfcb.conflict = opts
	return &CoinFiatUpsertBulk{
		create: cfcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinFiat.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cfcb *CoinFiatCreateBulk) OnConflictColumns(columns ...string) *CoinFiatUpsertBulk {
	cfcb.conflict = append(cfcb.conflict, sql.ConflictColumns(columns...))
	return &CoinFiatUpsertBulk{
		create: cfcb,
	}
}

// CoinFiatUpsertBulk is the builder for "upsert"-ing
// a bulk of CoinFiat nodes.
type CoinFiatUpsertBulk struct {
	create *CoinFiatCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CoinFiat.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coinfiat.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinFiatUpsertBulk) UpdateNewValues() *CoinFiatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(coinfiat.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoinFiat.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *CoinFiatUpsertBulk) Ignore() *CoinFiatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinFiatUpsertBulk) DoNothing() *CoinFiatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinFiatCreateBulk.OnConflict
// documentation for more info.
func (u *CoinFiatUpsertBulk) Update(set func(*CoinFiatUpsert)) *CoinFiatUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinFiatUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinFiatUpsertBulk) SetCreatedAt(v uint32) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinFiatUpsertBulk) AddCreatedAt(v uint32) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinFiatUpsertBulk) UpdateCreatedAt() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinFiatUpsertBulk) SetUpdatedAt(v uint32) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinFiatUpsertBulk) AddUpdatedAt(v uint32) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinFiatUpsertBulk) UpdateUpdatedAt() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinFiatUpsertBulk) SetDeletedAt(v uint32) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinFiatUpsertBulk) AddDeletedAt(v uint32) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinFiatUpsertBulk) UpdateDeletedAt() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetEntID sets the "ent_id" field.
func (u *CoinFiatUpsertBulk) SetEntID(v uuid.UUID) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetEntID(v)
	})
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CoinFiatUpsertBulk) UpdateEntID() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateEntID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinFiatUpsertBulk) SetCoinTypeID(v uuid.UUID) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinFiatUpsertBulk) UpdateCoinTypeID() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *CoinFiatUpsertBulk) ClearCoinTypeID() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetFiatID sets the "fiat_id" field.
func (u *CoinFiatUpsertBulk) SetFiatID(v uuid.UUID) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetFiatID(v)
	})
}

// UpdateFiatID sets the "fiat_id" field to the value that was provided on create.
func (u *CoinFiatUpsertBulk) UpdateFiatID() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateFiatID()
	})
}

// ClearFiatID clears the value of the "fiat_id" field.
func (u *CoinFiatUpsertBulk) ClearFiatID() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.ClearFiatID()
	})
}

// SetFeedType sets the "feed_type" field.
func (u *CoinFiatUpsertBulk) SetFeedType(v string) *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.SetFeedType(v)
	})
}

// UpdateFeedType sets the "feed_type" field to the value that was provided on create.
func (u *CoinFiatUpsertBulk) UpdateFeedType() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.UpdateFeedType()
	})
}

// ClearFeedType clears the value of the "feed_type" field.
func (u *CoinFiatUpsertBulk) ClearFeedType() *CoinFiatUpsertBulk {
	return u.Update(func(s *CoinFiatUpsert) {
		s.ClearFeedType()
	})
}

// Exec executes the query.
func (u *CoinFiatUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CoinFiatCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinFiatCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinFiatUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
