// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/chain-middleware/pkg/db/ent/coinfiatcurrency"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// CoinFiatCurrencyCreate is the builder for creating a CoinFiatCurrency entity.
type CoinFiatCurrencyCreate struct {
	config
	mutation *CoinFiatCurrencyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (cfcc *CoinFiatCurrencyCreate) SetCreatedAt(u uint32) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetCreatedAt(u)
	return cfcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableCreatedAt(u *uint32) *CoinFiatCurrencyCreate {
	if u != nil {
		cfcc.SetCreatedAt(*u)
	}
	return cfcc
}

// SetUpdatedAt sets the "updated_at" field.
func (cfcc *CoinFiatCurrencyCreate) SetUpdatedAt(u uint32) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetUpdatedAt(u)
	return cfcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableUpdatedAt(u *uint32) *CoinFiatCurrencyCreate {
	if u != nil {
		cfcc.SetUpdatedAt(*u)
	}
	return cfcc
}

// SetDeletedAt sets the "deleted_at" field.
func (cfcc *CoinFiatCurrencyCreate) SetDeletedAt(u uint32) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetDeletedAt(u)
	return cfcc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableDeletedAt(u *uint32) *CoinFiatCurrencyCreate {
	if u != nil {
		cfcc.SetDeletedAt(*u)
	}
	return cfcc
}

// SetEntID sets the "ent_id" field.
func (cfcc *CoinFiatCurrencyCreate) SetEntID(u uuid.UUID) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetEntID(u)
	return cfcc
}

// SetNillableEntID sets the "ent_id" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableEntID(u *uuid.UUID) *CoinFiatCurrencyCreate {
	if u != nil {
		cfcc.SetEntID(*u)
	}
	return cfcc
}

// SetCoinTypeID sets the "coin_type_id" field.
func (cfcc *CoinFiatCurrencyCreate) SetCoinTypeID(u uuid.UUID) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetCoinTypeID(u)
	return cfcc
}

// SetNillableCoinTypeID sets the "coin_type_id" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableCoinTypeID(u *uuid.UUID) *CoinFiatCurrencyCreate {
	if u != nil {
		cfcc.SetCoinTypeID(*u)
	}
	return cfcc
}

// SetFiatID sets the "fiat_id" field.
func (cfcc *CoinFiatCurrencyCreate) SetFiatID(u uuid.UUID) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetFiatID(u)
	return cfcc
}

// SetNillableFiatID sets the "fiat_id" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableFiatID(u *uuid.UUID) *CoinFiatCurrencyCreate {
	if u != nil {
		cfcc.SetFiatID(*u)
	}
	return cfcc
}

// SetFeedType sets the "feed_type" field.
func (cfcc *CoinFiatCurrencyCreate) SetFeedType(s string) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetFeedType(s)
	return cfcc
}

// SetNillableFeedType sets the "feed_type" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableFeedType(s *string) *CoinFiatCurrencyCreate {
	if s != nil {
		cfcc.SetFeedType(*s)
	}
	return cfcc
}

// SetMarketValueLow sets the "market_value_low" field.
func (cfcc *CoinFiatCurrencyCreate) SetMarketValueLow(d decimal.Decimal) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetMarketValueLow(d)
	return cfcc
}

// SetNillableMarketValueLow sets the "market_value_low" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableMarketValueLow(d *decimal.Decimal) *CoinFiatCurrencyCreate {
	if d != nil {
		cfcc.SetMarketValueLow(*d)
	}
	return cfcc
}

// SetMarketValueHigh sets the "market_value_high" field.
func (cfcc *CoinFiatCurrencyCreate) SetMarketValueHigh(d decimal.Decimal) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetMarketValueHigh(d)
	return cfcc
}

// SetNillableMarketValueHigh sets the "market_value_high" field if the given value is not nil.
func (cfcc *CoinFiatCurrencyCreate) SetNillableMarketValueHigh(d *decimal.Decimal) *CoinFiatCurrencyCreate {
	if d != nil {
		cfcc.SetMarketValueHigh(*d)
	}
	return cfcc
}

// SetID sets the "id" field.
func (cfcc *CoinFiatCurrencyCreate) SetID(i int) *CoinFiatCurrencyCreate {
	cfcc.mutation.SetID(i)
	return cfcc
}

// Mutation returns the CoinFiatCurrencyMutation object of the builder.
func (cfcc *CoinFiatCurrencyCreate) Mutation() *CoinFiatCurrencyMutation {
	return cfcc.mutation
}

// Save creates the CoinFiatCurrency in the database.
func (cfcc *CoinFiatCurrencyCreate) Save(ctx context.Context) (*CoinFiatCurrency, error) {
	var (
		err  error
		node *CoinFiatCurrency
	)
	if err := cfcc.defaults(); err != nil {
		return nil, err
	}
	if len(cfcc.hooks) == 0 {
		if err = cfcc.check(); err != nil {
			return nil, err
		}
		node, err = cfcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CoinFiatCurrencyMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cfcc.check(); err != nil {
				return nil, err
			}
			cfcc.mutation = mutation
			if node, err = cfcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cfcc.hooks) - 1; i >= 0; i-- {
			if cfcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cfcc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cfcc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*CoinFiatCurrency)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CoinFiatCurrencyMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cfcc *CoinFiatCurrencyCreate) SaveX(ctx context.Context) *CoinFiatCurrency {
	v, err := cfcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cfcc *CoinFiatCurrencyCreate) Exec(ctx context.Context) error {
	_, err := cfcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfcc *CoinFiatCurrencyCreate) ExecX(ctx context.Context) {
	if err := cfcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cfcc *CoinFiatCurrencyCreate) defaults() error {
	if _, ok := cfcc.mutation.CreatedAt(); !ok {
		if coinfiatcurrency.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized coinfiatcurrency.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := coinfiatcurrency.DefaultCreatedAt()
		cfcc.mutation.SetCreatedAt(v)
	}
	if _, ok := cfcc.mutation.UpdatedAt(); !ok {
		if coinfiatcurrency.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized coinfiatcurrency.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := coinfiatcurrency.DefaultUpdatedAt()
		cfcc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cfcc.mutation.DeletedAt(); !ok {
		if coinfiatcurrency.DefaultDeletedAt == nil {
			return fmt.Errorf("ent: uninitialized coinfiatcurrency.DefaultDeletedAt (forgotten import ent/runtime?)")
		}
		v := coinfiatcurrency.DefaultDeletedAt()
		cfcc.mutation.SetDeletedAt(v)
	}
	if _, ok := cfcc.mutation.EntID(); !ok {
		if coinfiatcurrency.DefaultEntID == nil {
			return fmt.Errorf("ent: uninitialized coinfiatcurrency.DefaultEntID (forgotten import ent/runtime?)")
		}
		v := coinfiatcurrency.DefaultEntID()
		cfcc.mutation.SetEntID(v)
	}
	if _, ok := cfcc.mutation.CoinTypeID(); !ok {
		if coinfiatcurrency.DefaultCoinTypeID == nil {
			return fmt.Errorf("ent: uninitialized coinfiatcurrency.DefaultCoinTypeID (forgotten import ent/runtime?)")
		}
		v := coinfiatcurrency.DefaultCoinTypeID()
		cfcc.mutation.SetCoinTypeID(v)
	}
	if _, ok := cfcc.mutation.FiatID(); !ok {
		if coinfiatcurrency.DefaultFiatID == nil {
			return fmt.Errorf("ent: uninitialized coinfiatcurrency.DefaultFiatID (forgotten import ent/runtime?)")
		}
		v := coinfiatcurrency.DefaultFiatID()
		cfcc.mutation.SetFiatID(v)
	}
	if _, ok := cfcc.mutation.FeedType(); !ok {
		v := coinfiatcurrency.DefaultFeedType
		cfcc.mutation.SetFeedType(v)
	}
	if _, ok := cfcc.mutation.MarketValueLow(); !ok {
		v := coinfiatcurrency.DefaultMarketValueLow
		cfcc.mutation.SetMarketValueLow(v)
	}
	if _, ok := cfcc.mutation.MarketValueHigh(); !ok {
		v := coinfiatcurrency.DefaultMarketValueHigh
		cfcc.mutation.SetMarketValueHigh(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (cfcc *CoinFiatCurrencyCreate) check() error {
	if _, ok := cfcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CoinFiatCurrency.created_at"`)}
	}
	if _, ok := cfcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CoinFiatCurrency.updated_at"`)}
	}
	if _, ok := cfcc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "CoinFiatCurrency.deleted_at"`)}
	}
	if _, ok := cfcc.mutation.EntID(); !ok {
		return &ValidationError{Name: "ent_id", err: errors.New(`ent: missing required field "CoinFiatCurrency.ent_id"`)}
	}
	return nil
}

func (cfcc *CoinFiatCurrencyCreate) sqlSave(ctx context.Context) (*CoinFiatCurrency, error) {
	_node, _spec := cfcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cfcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (cfcc *CoinFiatCurrencyCreate) createSpec() (*CoinFiatCurrency, *sqlgraph.CreateSpec) {
	var (
		_node = &CoinFiatCurrency{config: cfcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: coinfiatcurrency.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: coinfiatcurrency.FieldID,
			},
		}
	)
	_spec.OnConflict = cfcc.conflict
	if id, ok := cfcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cfcc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinfiatcurrency.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := cfcc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinfiatcurrency.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := cfcc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: coinfiatcurrency.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := cfcc.mutation.EntID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: coinfiatcurrency.FieldEntID,
		})
		_node.EntID = value
	}
	if value, ok := cfcc.mutation.CoinTypeID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: coinfiatcurrency.FieldCoinTypeID,
		})
		_node.CoinTypeID = value
	}
	if value, ok := cfcc.mutation.FiatID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: coinfiatcurrency.FieldFiatID,
		})
		_node.FiatID = value
	}
	if value, ok := cfcc.mutation.FeedType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: coinfiatcurrency.FieldFeedType,
		})
		_node.FeedType = value
	}
	if value, ok := cfcc.mutation.MarketValueLow(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: coinfiatcurrency.FieldMarketValueLow,
		})
		_node.MarketValueLow = value
	}
	if value, ok := cfcc.mutation.MarketValueHigh(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: coinfiatcurrency.FieldMarketValueHigh,
		})
		_node.MarketValueHigh = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinFiatCurrency.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinFiatCurrencyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cfcc *CoinFiatCurrencyCreate) OnConflict(opts ...sql.ConflictOption) *CoinFiatCurrencyUpsertOne {
	cfcc.conflict = opts
	return &CoinFiatCurrencyUpsertOne{
		create: cfcc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinFiatCurrency.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cfcc *CoinFiatCurrencyCreate) OnConflictColumns(columns ...string) *CoinFiatCurrencyUpsertOne {
	cfcc.conflict = append(cfcc.conflict, sql.ConflictColumns(columns...))
	return &CoinFiatCurrencyUpsertOne{
		create: cfcc,
	}
}

type (
	// CoinFiatCurrencyUpsertOne is the builder for "upsert"-ing
	//  one CoinFiatCurrency node.
	CoinFiatCurrencyUpsertOne struct {
		create *CoinFiatCurrencyCreate
	}

	// CoinFiatCurrencyUpsert is the "OnConflict" setter.
	CoinFiatCurrencyUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *CoinFiatCurrencyUpsert) SetCreatedAt(v uint32) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateCreatedAt() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldCreatedAt)
	return u
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinFiatCurrencyUpsert) AddCreatedAt(v uint32) *CoinFiatCurrencyUpsert {
	u.Add(coinfiatcurrency.FieldCreatedAt, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinFiatCurrencyUpsert) SetUpdatedAt(v uint32) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateUpdatedAt() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinFiatCurrencyUpsert) AddUpdatedAt(v uint32) *CoinFiatCurrencyUpsert {
	u.Add(coinfiatcurrency.FieldUpdatedAt, v)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinFiatCurrencyUpsert) SetDeletedAt(v uint32) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateDeletedAt() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinFiatCurrencyUpsert) AddDeletedAt(v uint32) *CoinFiatCurrencyUpsert {
	u.Add(coinfiatcurrency.FieldDeletedAt, v)
	return u
}

// SetEntID sets the "ent_id" field.
func (u *CoinFiatCurrencyUpsert) SetEntID(v uuid.UUID) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldEntID, v)
	return u
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateEntID() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldEntID)
	return u
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinFiatCurrencyUpsert) SetCoinTypeID(v uuid.UUID) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldCoinTypeID, v)
	return u
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateCoinTypeID() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldCoinTypeID)
	return u
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *CoinFiatCurrencyUpsert) ClearCoinTypeID() *CoinFiatCurrencyUpsert {
	u.SetNull(coinfiatcurrency.FieldCoinTypeID)
	return u
}

// SetFiatID sets the "fiat_id" field.
func (u *CoinFiatCurrencyUpsert) SetFiatID(v uuid.UUID) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldFiatID, v)
	return u
}

// UpdateFiatID sets the "fiat_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateFiatID() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldFiatID)
	return u
}

// ClearFiatID clears the value of the "fiat_id" field.
func (u *CoinFiatCurrencyUpsert) ClearFiatID() *CoinFiatCurrencyUpsert {
	u.SetNull(coinfiatcurrency.FieldFiatID)
	return u
}

// SetFeedType sets the "feed_type" field.
func (u *CoinFiatCurrencyUpsert) SetFeedType(v string) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldFeedType, v)
	return u
}

// UpdateFeedType sets the "feed_type" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateFeedType() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldFeedType)
	return u
}

// ClearFeedType clears the value of the "feed_type" field.
func (u *CoinFiatCurrencyUpsert) ClearFeedType() *CoinFiatCurrencyUpsert {
	u.SetNull(coinfiatcurrency.FieldFeedType)
	return u
}

// SetMarketValueLow sets the "market_value_low" field.
func (u *CoinFiatCurrencyUpsert) SetMarketValueLow(v decimal.Decimal) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldMarketValueLow, v)
	return u
}

// UpdateMarketValueLow sets the "market_value_low" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateMarketValueLow() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldMarketValueLow)
	return u
}

// ClearMarketValueLow clears the value of the "market_value_low" field.
func (u *CoinFiatCurrencyUpsert) ClearMarketValueLow() *CoinFiatCurrencyUpsert {
	u.SetNull(coinfiatcurrency.FieldMarketValueLow)
	return u
}

// SetMarketValueHigh sets the "market_value_high" field.
func (u *CoinFiatCurrencyUpsert) SetMarketValueHigh(v decimal.Decimal) *CoinFiatCurrencyUpsert {
	u.Set(coinfiatcurrency.FieldMarketValueHigh, v)
	return u
}

// UpdateMarketValueHigh sets the "market_value_high" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsert) UpdateMarketValueHigh() *CoinFiatCurrencyUpsert {
	u.SetExcluded(coinfiatcurrency.FieldMarketValueHigh)
	return u
}

// ClearMarketValueHigh clears the value of the "market_value_high" field.
func (u *CoinFiatCurrencyUpsert) ClearMarketValueHigh() *CoinFiatCurrencyUpsert {
	u.SetNull(coinfiatcurrency.FieldMarketValueHigh)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CoinFiatCurrency.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coinfiatcurrency.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinFiatCurrencyUpsertOne) UpdateNewValues() *CoinFiatCurrencyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(coinfiatcurrency.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.CoinFiatCurrency.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *CoinFiatCurrencyUpsertOne) Ignore() *CoinFiatCurrencyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinFiatCurrencyUpsertOne) DoNothing() *CoinFiatCurrencyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinFiatCurrencyCreate.OnConflict
// documentation for more info.
func (u *CoinFiatCurrencyUpsertOne) Update(set func(*CoinFiatCurrencyUpsert)) *CoinFiatCurrencyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinFiatCurrencyUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinFiatCurrencyUpsertOne) SetCreatedAt(v uint32) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinFiatCurrencyUpsertOne) AddCreatedAt(v uint32) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateCreatedAt() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinFiatCurrencyUpsertOne) SetUpdatedAt(v uint32) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinFiatCurrencyUpsertOne) AddUpdatedAt(v uint32) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateUpdatedAt() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinFiatCurrencyUpsertOne) SetDeletedAt(v uint32) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinFiatCurrencyUpsertOne) AddDeletedAt(v uint32) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateDeletedAt() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetEntID sets the "ent_id" field.
func (u *CoinFiatCurrencyUpsertOne) SetEntID(v uuid.UUID) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetEntID(v)
	})
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateEntID() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateEntID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinFiatCurrencyUpsertOne) SetCoinTypeID(v uuid.UUID) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateCoinTypeID() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *CoinFiatCurrencyUpsertOne) ClearCoinTypeID() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetFiatID sets the "fiat_id" field.
func (u *CoinFiatCurrencyUpsertOne) SetFiatID(v uuid.UUID) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetFiatID(v)
	})
}

// UpdateFiatID sets the "fiat_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateFiatID() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateFiatID()
	})
}

// ClearFiatID clears the value of the "fiat_id" field.
func (u *CoinFiatCurrencyUpsertOne) ClearFiatID() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearFiatID()
	})
}

// SetFeedType sets the "feed_type" field.
func (u *CoinFiatCurrencyUpsertOne) SetFeedType(v string) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetFeedType(v)
	})
}

// UpdateFeedType sets the "feed_type" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateFeedType() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateFeedType()
	})
}

// ClearFeedType clears the value of the "feed_type" field.
func (u *CoinFiatCurrencyUpsertOne) ClearFeedType() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearFeedType()
	})
}

// SetMarketValueLow sets the "market_value_low" field.
func (u *CoinFiatCurrencyUpsertOne) SetMarketValueLow(v decimal.Decimal) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetMarketValueLow(v)
	})
}

// UpdateMarketValueLow sets the "market_value_low" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateMarketValueLow() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateMarketValueLow()
	})
}

// ClearMarketValueLow clears the value of the "market_value_low" field.
func (u *CoinFiatCurrencyUpsertOne) ClearMarketValueLow() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearMarketValueLow()
	})
}

// SetMarketValueHigh sets the "market_value_high" field.
func (u *CoinFiatCurrencyUpsertOne) SetMarketValueHigh(v decimal.Decimal) *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetMarketValueHigh(v)
	})
}

// UpdateMarketValueHigh sets the "market_value_high" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertOne) UpdateMarketValueHigh() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateMarketValueHigh()
	})
}

// ClearMarketValueHigh clears the value of the "market_value_high" field.
func (u *CoinFiatCurrencyUpsertOne) ClearMarketValueHigh() *CoinFiatCurrencyUpsertOne {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearMarketValueHigh()
	})
}

// Exec executes the query.
func (u *CoinFiatCurrencyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinFiatCurrencyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinFiatCurrencyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CoinFiatCurrencyUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CoinFiatCurrencyUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CoinFiatCurrencyCreateBulk is the builder for creating many CoinFiatCurrency entities in bulk.
type CoinFiatCurrencyCreateBulk struct {
	config
	builders []*CoinFiatCurrencyCreate
	conflict []sql.ConflictOption
}

// Save creates the CoinFiatCurrency entities in the database.
func (cfccb *CoinFiatCurrencyCreateBulk) Save(ctx context.Context) ([]*CoinFiatCurrency, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cfccb.builders))
	nodes := make([]*CoinFiatCurrency, len(cfccb.builders))
	mutators := make([]Mutator, len(cfccb.builders))
	for i := range cfccb.builders {
		func(i int, root context.Context) {
			builder := cfccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CoinFiatCurrencyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cfccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = cfccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cfccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cfccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cfccb *CoinFiatCurrencyCreateBulk) SaveX(ctx context.Context) []*CoinFiatCurrency {
	v, err := cfccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cfccb *CoinFiatCurrencyCreateBulk) Exec(ctx context.Context) error {
	_, err := cfccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cfccb *CoinFiatCurrencyCreateBulk) ExecX(ctx context.Context) {
	if err := cfccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CoinFiatCurrency.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CoinFiatCurrencyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (cfccb *CoinFiatCurrencyCreateBulk) OnConflict(opts ...sql.ConflictOption) *CoinFiatCurrencyUpsertBulk {
	cfccb.conflict = opts
	return &CoinFiatCurrencyUpsertBulk{
		create: cfccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CoinFiatCurrency.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (cfccb *CoinFiatCurrencyCreateBulk) OnConflictColumns(columns ...string) *CoinFiatCurrencyUpsertBulk {
	cfccb.conflict = append(cfccb.conflict, sql.ConflictColumns(columns...))
	return &CoinFiatCurrencyUpsertBulk{
		create: cfccb,
	}
}

// CoinFiatCurrencyUpsertBulk is the builder for "upsert"-ing
// a bulk of CoinFiatCurrency nodes.
type CoinFiatCurrencyUpsertBulk struct {
	create *CoinFiatCurrencyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CoinFiatCurrency.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(coinfiatcurrency.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *CoinFiatCurrencyUpsertBulk) UpdateNewValues() *CoinFiatCurrencyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(coinfiatcurrency.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CoinFiatCurrency.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *CoinFiatCurrencyUpsertBulk) Ignore() *CoinFiatCurrencyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CoinFiatCurrencyUpsertBulk) DoNothing() *CoinFiatCurrencyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CoinFiatCurrencyCreateBulk.OnConflict
// documentation for more info.
func (u *CoinFiatCurrencyUpsertBulk) Update(set func(*CoinFiatCurrencyUpsert)) *CoinFiatCurrencyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CoinFiatCurrencyUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CoinFiatCurrencyUpsertBulk) SetCreatedAt(v uint32) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetCreatedAt(v)
	})
}

// AddCreatedAt adds v to the "created_at" field.
func (u *CoinFiatCurrencyUpsertBulk) AddCreatedAt(v uint32) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.AddCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateCreatedAt() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CoinFiatCurrencyUpsertBulk) SetUpdatedAt(v uint32) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *CoinFiatCurrencyUpsertBulk) AddUpdatedAt(v uint32) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateUpdatedAt() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CoinFiatCurrencyUpsertBulk) SetDeletedAt(v uint32) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *CoinFiatCurrencyUpsertBulk) AddDeletedAt(v uint32) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateDeletedAt() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetEntID sets the "ent_id" field.
func (u *CoinFiatCurrencyUpsertBulk) SetEntID(v uuid.UUID) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetEntID(v)
	})
}

// UpdateEntID sets the "ent_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateEntID() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateEntID()
	})
}

// SetCoinTypeID sets the "coin_type_id" field.
func (u *CoinFiatCurrencyUpsertBulk) SetCoinTypeID(v uuid.UUID) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetCoinTypeID(v)
	})
}

// UpdateCoinTypeID sets the "coin_type_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateCoinTypeID() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateCoinTypeID()
	})
}

// ClearCoinTypeID clears the value of the "coin_type_id" field.
func (u *CoinFiatCurrencyUpsertBulk) ClearCoinTypeID() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearCoinTypeID()
	})
}

// SetFiatID sets the "fiat_id" field.
func (u *CoinFiatCurrencyUpsertBulk) SetFiatID(v uuid.UUID) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetFiatID(v)
	})
}

// UpdateFiatID sets the "fiat_id" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateFiatID() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateFiatID()
	})
}

// ClearFiatID clears the value of the "fiat_id" field.
func (u *CoinFiatCurrencyUpsertBulk) ClearFiatID() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearFiatID()
	})
}

// SetFeedType sets the "feed_type" field.
func (u *CoinFiatCurrencyUpsertBulk) SetFeedType(v string) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetFeedType(v)
	})
}

// UpdateFeedType sets the "feed_type" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateFeedType() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateFeedType()
	})
}

// ClearFeedType clears the value of the "feed_type" field.
func (u *CoinFiatCurrencyUpsertBulk) ClearFeedType() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearFeedType()
	})
}

// SetMarketValueLow sets the "market_value_low" field.
func (u *CoinFiatCurrencyUpsertBulk) SetMarketValueLow(v decimal.Decimal) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetMarketValueLow(v)
	})
}

// UpdateMarketValueLow sets the "market_value_low" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateMarketValueLow() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateMarketValueLow()
	})
}

// ClearMarketValueLow clears the value of the "market_value_low" field.
func (u *CoinFiatCurrencyUpsertBulk) ClearMarketValueLow() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearMarketValueLow()
	})
}

// SetMarketValueHigh sets the "market_value_high" field.
func (u *CoinFiatCurrencyUpsertBulk) SetMarketValueHigh(v decimal.Decimal) *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.SetMarketValueHigh(v)
	})
}

// UpdateMarketValueHigh sets the "market_value_high" field to the value that was provided on create.
func (u *CoinFiatCurrencyUpsertBulk) UpdateMarketValueHigh() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.UpdateMarketValueHigh()
	})
}

// ClearMarketValueHigh clears the value of the "market_value_high" field.
func (u *CoinFiatCurrencyUpsertBulk) ClearMarketValueHigh() *CoinFiatCurrencyUpsertBulk {
	return u.Update(func(s *CoinFiatCurrencyUpsert) {
		s.ClearMarketValueHigh()
	})
}

// Exec executes the query.
func (u *CoinFiatCurrencyUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CoinFiatCurrencyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CoinFiatCurrencyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CoinFiatCurrencyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
