// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/chain-middleware/pkg/db/ent/coinusedfor"
	"github.com/NpoolPlatform/chain-middleware/pkg/db/ent/predicate"
)

// CoinUsedForQuery is the builder for querying CoinUsedFor entities.
type CoinUsedForQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CoinUsedFor
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CoinUsedForQuery builder.
func (cufq *CoinUsedForQuery) Where(ps ...predicate.CoinUsedFor) *CoinUsedForQuery {
	cufq.predicates = append(cufq.predicates, ps...)
	return cufq
}

// Limit adds a limit step to the query.
func (cufq *CoinUsedForQuery) Limit(limit int) *CoinUsedForQuery {
	cufq.limit = &limit
	return cufq
}

// Offset adds an offset step to the query.
func (cufq *CoinUsedForQuery) Offset(offset int) *CoinUsedForQuery {
	cufq.offset = &offset
	return cufq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cufq *CoinUsedForQuery) Unique(unique bool) *CoinUsedForQuery {
	cufq.unique = &unique
	return cufq
}

// Order adds an order step to the query.
func (cufq *CoinUsedForQuery) Order(o ...OrderFunc) *CoinUsedForQuery {
	cufq.order = append(cufq.order, o...)
	return cufq
}

// First returns the first CoinUsedFor entity from the query.
// Returns a *NotFoundError when no CoinUsedFor was found.
func (cufq *CoinUsedForQuery) First(ctx context.Context) (*CoinUsedFor, error) {
	nodes, err := cufq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{coinusedfor.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cufq *CoinUsedForQuery) FirstX(ctx context.Context) *CoinUsedFor {
	node, err := cufq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CoinUsedFor ID from the query.
// Returns a *NotFoundError when no CoinUsedFor ID was found.
func (cufq *CoinUsedForQuery) FirstID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = cufq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{coinusedfor.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cufq *CoinUsedForQuery) FirstIDX(ctx context.Context) uint32 {
	id, err := cufq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CoinUsedFor entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CoinUsedFor entity is found.
// Returns a *NotFoundError when no CoinUsedFor entities are found.
func (cufq *CoinUsedForQuery) Only(ctx context.Context) (*CoinUsedFor, error) {
	nodes, err := cufq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{coinusedfor.Label}
	default:
		return nil, &NotSingularError{coinusedfor.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cufq *CoinUsedForQuery) OnlyX(ctx context.Context) *CoinUsedFor {
	node, err := cufq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CoinUsedFor ID in the query.
// Returns a *NotSingularError when more than one CoinUsedFor ID is found.
// Returns a *NotFoundError when no entities are found.
func (cufq *CoinUsedForQuery) OnlyID(ctx context.Context) (id uint32, err error) {
	var ids []uint32
	if ids, err = cufq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{coinusedfor.Label}
	default:
		err = &NotSingularError{coinusedfor.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cufq *CoinUsedForQuery) OnlyIDX(ctx context.Context) uint32 {
	id, err := cufq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CoinUsedFors.
func (cufq *CoinUsedForQuery) All(ctx context.Context) ([]*CoinUsedFor, error) {
	if err := cufq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cufq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cufq *CoinUsedForQuery) AllX(ctx context.Context) []*CoinUsedFor {
	nodes, err := cufq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CoinUsedFor IDs.
func (cufq *CoinUsedForQuery) IDs(ctx context.Context) ([]uint32, error) {
	var ids []uint32
	if err := cufq.Select(coinusedfor.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cufq *CoinUsedForQuery) IDsX(ctx context.Context) []uint32 {
	ids, err := cufq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cufq *CoinUsedForQuery) Count(ctx context.Context) (int, error) {
	if err := cufq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cufq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cufq *CoinUsedForQuery) CountX(ctx context.Context) int {
	count, err := cufq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cufq *CoinUsedForQuery) Exist(ctx context.Context) (bool, error) {
	if err := cufq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cufq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cufq *CoinUsedForQuery) ExistX(ctx context.Context) bool {
	exist, err := cufq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CoinUsedForQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cufq *CoinUsedForQuery) Clone() *CoinUsedForQuery {
	if cufq == nil {
		return nil
	}
	return &CoinUsedForQuery{
		config:     cufq.config,
		limit:      cufq.limit,
		offset:     cufq.offset,
		order:      append([]OrderFunc{}, cufq.order...),
		predicates: append([]predicate.CoinUsedFor{}, cufq.predicates...),
		// clone intermediate query.
		sql:    cufq.sql.Clone(),
		path:   cufq.path,
		unique: cufq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CoinUsedFor.Query().
//		GroupBy(coinusedfor.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cufq *CoinUsedForQuery) GroupBy(field string, fields ...string) *CoinUsedForGroupBy {
	grbuild := &CoinUsedForGroupBy{config: cufq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cufq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cufq.sqlQuery(ctx), nil
	}
	grbuild.label = coinusedfor.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt uint32 `json:"created_at,omitempty"`
//	}
//
//	client.CoinUsedFor.Query().
//		Select(coinusedfor.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (cufq *CoinUsedForQuery) Select(fields ...string) *CoinUsedForSelect {
	cufq.fields = append(cufq.fields, fields...)
	selbuild := &CoinUsedForSelect{CoinUsedForQuery: cufq}
	selbuild.label = coinusedfor.Label
	selbuild.flds, selbuild.scan = &cufq.fields, selbuild.Scan
	return selbuild
}

func (cufq *CoinUsedForQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cufq.fields {
		if !coinusedfor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cufq.path != nil {
		prev, err := cufq.path(ctx)
		if err != nil {
			return err
		}
		cufq.sql = prev
	}
	if coinusedfor.Policy == nil {
		return errors.New("ent: uninitialized coinusedfor.Policy (forgotten import ent/runtime?)")
	}
	if err := coinusedfor.Policy.EvalQuery(ctx, cufq); err != nil {
		return err
	}
	return nil
}

func (cufq *CoinUsedForQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CoinUsedFor, error) {
	var (
		nodes = []*CoinUsedFor{}
		_spec = cufq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*CoinUsedFor).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &CoinUsedFor{config: cufq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(cufq.modifiers) > 0 {
		_spec.Modifiers = cufq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cufq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cufq *CoinUsedForQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cufq.querySpec()
	if len(cufq.modifiers) > 0 {
		_spec.Modifiers = cufq.modifiers
	}
	_spec.Node.Columns = cufq.fields
	if len(cufq.fields) > 0 {
		_spec.Unique = cufq.unique != nil && *cufq.unique
	}
	return sqlgraph.CountNodes(ctx, cufq.driver, _spec)
}

func (cufq *CoinUsedForQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := cufq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (cufq *CoinUsedForQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   coinusedfor.Table,
			Columns: coinusedfor.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: coinusedfor.FieldID,
			},
		},
		From:   cufq.sql,
		Unique: true,
	}
	if unique := cufq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cufq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, coinusedfor.FieldID)
		for i := range fields {
			if fields[i] != coinusedfor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cufq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cufq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cufq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cufq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cufq *CoinUsedForQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cufq.driver.Dialect())
	t1 := builder.Table(coinusedfor.Table)
	columns := cufq.fields
	if len(columns) == 0 {
		columns = coinusedfor.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cufq.sql != nil {
		selector = cufq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cufq.unique != nil && *cufq.unique {
		selector.Distinct()
	}
	for _, m := range cufq.modifiers {
		m(selector)
	}
	for _, p := range cufq.predicates {
		p(selector)
	}
	for _, p := range cufq.order {
		p(selector)
	}
	if offset := cufq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cufq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (cufq *CoinUsedForQuery) ForUpdate(opts ...sql.LockOption) *CoinUsedForQuery {
	if cufq.driver.Dialect() == dialect.Postgres {
		cufq.Unique(false)
	}
	cufq.modifiers = append(cufq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return cufq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (cufq *CoinUsedForQuery) ForShare(opts ...sql.LockOption) *CoinUsedForQuery {
	if cufq.driver.Dialect() == dialect.Postgres {
		cufq.Unique(false)
	}
	cufq.modifiers = append(cufq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return cufq
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cufq *CoinUsedForQuery) Modify(modifiers ...func(s *sql.Selector)) *CoinUsedForSelect {
	cufq.modifiers = append(cufq.modifiers, modifiers...)
	return cufq.Select()
}

// CoinUsedForGroupBy is the group-by builder for CoinUsedFor entities.
type CoinUsedForGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cufgb *CoinUsedForGroupBy) Aggregate(fns ...AggregateFunc) *CoinUsedForGroupBy {
	cufgb.fns = append(cufgb.fns, fns...)
	return cufgb
}

// Scan applies the group-by query and scans the result into the given value.
func (cufgb *CoinUsedForGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cufgb.path(ctx)
	if err != nil {
		return err
	}
	cufgb.sql = query
	return cufgb.sqlScan(ctx, v)
}

func (cufgb *CoinUsedForGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cufgb.fields {
		if !coinusedfor.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cufgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cufgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cufgb *CoinUsedForGroupBy) sqlQuery() *sql.Selector {
	selector := cufgb.sql.Select()
	aggregation := make([]string, 0, len(cufgb.fns))
	for _, fn := range cufgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cufgb.fields)+len(cufgb.fns))
		for _, f := range cufgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cufgb.fields...)...)
}

// CoinUsedForSelect is the builder for selecting fields of CoinUsedFor entities.
type CoinUsedForSelect struct {
	*CoinUsedForQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cufs *CoinUsedForSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cufs.prepareQuery(ctx); err != nil {
		return err
	}
	cufs.sql = cufs.CoinUsedForQuery.sqlQuery(ctx)
	return cufs.sqlScan(ctx, v)
}

func (cufs *CoinUsedForSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cufs.sql.Query()
	if err := cufs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (cufs *CoinUsedForSelect) Modify(modifiers ...func(s *sql.Selector)) *CoinUsedForSelect {
	cufs.modifiers = append(cufs.modifiers, modifiers...)
	return cufs
}
