// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/chain-middleware/pkg/db/ent/fiatcurrencyhistory"
	"github.com/NpoolPlatform/chain-middleware/pkg/db/ent/predicate"
)

// FiatCurrencyHistoryDelete is the builder for deleting a FiatCurrencyHistory entity.
type FiatCurrencyHistoryDelete struct {
	config
	hooks    []Hook
	mutation *FiatCurrencyHistoryMutation
}

// Where appends a list predicates to the FiatCurrencyHistoryDelete builder.
func (fchd *FiatCurrencyHistoryDelete) Where(ps ...predicate.FiatCurrencyHistory) *FiatCurrencyHistoryDelete {
	fchd.mutation.Where(ps...)
	return fchd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fchd *FiatCurrencyHistoryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fchd.hooks) == 0 {
		affected, err = fchd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FiatCurrencyHistoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fchd.mutation = mutation
			affected, err = fchd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fchd.hooks) - 1; i >= 0; i-- {
			if fchd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fchd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fchd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (fchd *FiatCurrencyHistoryDelete) ExecX(ctx context.Context) int {
	n, err := fchd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fchd *FiatCurrencyHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: fiatcurrencyhistory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: fiatcurrencyhistory.FieldID,
			},
		},
	}
	if ps := fchd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fchd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// FiatCurrencyHistoryDeleteOne is the builder for deleting a single FiatCurrencyHistory entity.
type FiatCurrencyHistoryDeleteOne struct {
	fchd *FiatCurrencyHistoryDelete
}

// Exec executes the deletion query.
func (fchdo *FiatCurrencyHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := fchdo.fchd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fiatcurrencyhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fchdo *FiatCurrencyHistoryDeleteOne) ExecX(ctx context.Context) {
	fchdo.fchd.ExecX(ctx)
}
