// Code generated by ent, DO NOT EDIT.

package fiatcurrencyfeed

import (
	"entgo.io/ent"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the fiatcurrencyfeed type in the database.
	Label = "fiat_currency_feed"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldFiatID holds the string denoting the fiat_id field in the database.
	FieldFiatID = "fiat_id"
	// FieldFeedType holds the string denoting the feed_type field in the database.
	FieldFeedType = "feed_type"
	// FieldFeedFiatName holds the string denoting the feed_fiat_name field in the database.
	FieldFeedFiatName = "feed_fiat_name"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// Table holds the table name of the fiatcurrencyfeed in the database.
	Table = "fiat_currency_feeds"
)

// Columns holds all SQL columns for fiatcurrencyfeed fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldFiatID,
	FieldFeedType,
	FieldFeedFiatName,
	FieldDisabled,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/NpoolPlatform/chain-middleware/pkg/db/ent/runtime"
//
var (
	Hooks  [1]ent.Hook
	Policy ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() uint32
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() uint32
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() uint32
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() uint32
	// DefaultFiatID holds the default value on creation for the "fiat_id" field.
	DefaultFiatID func() uuid.UUID
	// DefaultFeedType holds the default value on creation for the "feed_type" field.
	DefaultFeedType string
	// DefaultFeedFiatName holds the default value on creation for the "feed_fiat_name" field.
	DefaultFeedFiatName string
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
