// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppCoin is the predicate function for appcoin builders.
type AppCoin func(*sql.Selector)

// ChainBase is the predicate function for chainbase builders.
type ChainBase func(*sql.Selector)

// CoinBase is the predicate function for coinbase builders.
type CoinBase func(*sql.Selector)

// CoinDescription is the predicate function for coindescription builders.
type CoinDescription func(*sql.Selector)

// CoinExtra is the predicate function for coinextra builders.
type CoinExtra func(*sql.Selector)

// CoinFiat is the predicate function for coinfiat builders.
type CoinFiat func(*sql.Selector)

// CoinFiatCurrency is the predicate function for coinfiatcurrency builders.
type CoinFiatCurrency func(*sql.Selector)

// CoinFiatCurrencyHistory is the predicate function for coinfiatcurrencyhistory builders.
type CoinFiatCurrencyHistory func(*sql.Selector)

// CoinUsedFor is the predicate function for coinusedfor builders.
type CoinUsedFor func(*sql.Selector)

// Currency is the predicate function for currency builders.
type Currency func(*sql.Selector)

// CurrencyFeed is the predicate function for currencyfeed builders.
type CurrencyFeed func(*sql.Selector)

// CurrencyHistory is the predicate function for currencyhistory builders.
type CurrencyHistory func(*sql.Selector)

// ExchangeRate is the predicate function for exchangerate builders.
type ExchangeRate func(*sql.Selector)

// Fiat is the predicate function for fiat builders.
type Fiat func(*sql.Selector)

// FiatCurrency is the predicate function for fiatcurrency builders.
type FiatCurrency func(*sql.Selector)

// FiatCurrencyFeed is the predicate function for fiatcurrencyfeed builders.
type FiatCurrencyFeed func(*sql.Selector)

// FiatCurrencyHistory is the predicate function for fiatcurrencyhistory builders.
type FiatCurrencyHistory func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// Tran is the predicate function for tran builders.
type Tran func(*sql.Selector)
